# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SAAMClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '0.9.1'
  # Pods for SAAMClient
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
